project:
  type: book
  output-dir: docs
book:
  title: "GEOG0023 -- Learning Diary" 
  navbar: 
    logo: ucl.jpg
    collapse: true
    collapse-below: lg
    background: info
    search: true
  author: "Ling Yi Cheung"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - summary.qmd
    - references.qmd

title-block-banner: /Users/sophiac/Desktop/Remotely sensing/Week2_quarto/Week2_Quarto/figures/Hong-Kong.jpeg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

