project:
  type: book
  output-dir: docs
book:
  title: "GEOG0023 -- Learning Diary" 
  navbar: 
    logo: /Users/sophiac/Desktop/Remotely sensing/Week2_quarto/Week2_Quarto/figures/ucl.jpg
    collapse: true
    collapse-below: lg
    background: info
    style: docked
    search: true
    pinned: true
    align: center
  author: "Ling Yi Cheung"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - summary.qmd
    - references.qmd
 
bibliography: references.bib
 
format:
  html:
    theme: "styles.css"




   

