project:
  type: book
  output-dir: docs
book:
  title: "GEOG0023 -- Learning Diary" 
  navbar: 
    logo: figures/ucl.jpg
    collapse: true
    collapse-below: lg
    background: "light"
    style: docked
    search: true
    right:
      - icon: github
    pinned: true
    align: center
  sidebar:
    title: "CASA0023"
    style: floating
    reader-mode: true
  repo-url: https://github.com/Sophialyc/GEOG0023_quarto.git
  author: "Ling Yi Cheung"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - summary.qmd
    - references.qmd
 
bibliography: references.bib
 
format:
  html:
    theme:
      light: [Lux, flatly]
      dark: [Lux, darkly]
    css: styles.css
    toc: false
    title-block-banner: "figures/hk.jpeg"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: "body"




   

