<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GEOG0023 – Learning Diary - 8&nbsp; Week 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Week7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>
    .quarto-title-block .quarto-title-banner {
      background-image: url(figures/hk.jpeg);
background-size: cover;
    }
    </style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./figures/ucl.jpg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">GEOG0023 – Learning Diary</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Sophialyc/GEOG0023_quarto.git"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Week 8</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Week 8</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Week 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Week 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Week 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Week 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Week 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Week 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week7.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Week 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Week8.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Week 8</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary-of-lecture-8" id="toc-summary-of-lecture-8" class="nav-link active" data-scroll-target="#summary-of-lecture-8"><span class="toc-section-number">8.1</span>  Summary of Lecture 8</a>
  <ul class="collapse">
  <li><a href="#global-policy" id="toc-global-policy" class="nav-link" data-scroll-target="#global-policy"><span class="toc-section-number">8.1.1</span>  Global policy</a></li>
  <li><a href="#hong-kongs-uhi" id="toc-hong-kongs-uhi" class="nav-link" data-scroll-target="#hong-kongs-uhi"><span class="toc-section-number">8.1.2</span>  Hong Kong’s UHI</a></li>
  </ul></li>
  <li><a href="#application" id="toc-application" class="nav-link" data-scroll-target="#application"><span class="toc-section-number">8.2</span>  Application</a>
  <ul class="collapse">
  <li><a href="#local-policy" id="toc-local-policy" class="nav-link" data-scroll-target="#local-policy"><span class="toc-section-number">8.2.1</span>  Local Policy</a></li>
  </ul></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection"><span class="toc-section-number">8.3</span>  Reflection</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div style="text-align: justify">

<section id="summary-of-lecture-8" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="summary-of-lecture-8"><span class="header-section-number">8.1</span> Summary of Lecture 8</h2>
<p>This week, we covered Urban Heat Island (UHI) and policy related to it. UHI effects occur when cities replace natural land cover with dense concentrations of pavement, buildings and urban structures that absorb and retain heat. In highly concentrated urban areas with limited greenery, the area will become “islands” of higher temperatures relative to outlying areas <span class="citation" data-cites="usepa2014">(<a href="#ref-usepa2014" role="doc-biblioref">US EPA 2014</a>)</span>. There are factors that cause and intensify UHI, such as heat generated from human activities, weather and geography and reduced natural landscapes in urban areas. However, from the view of remote sensing, there are two main factors that is identified as UHI from the images, including the dark surfaces that retain heat and less vegetation to regulate temperature. Other than that, another factor would be the low <strong>Sky View Factor(SVF)</strong>,how much we can see the sky when we look up. The magnitude of UHI in world cities are shown below, showing the variations in different regions.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-019-1512-9/MediaObjects/41586_2019_1512_Fig2_HTML.png?as=webp" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Map of summertime UHI intensity in world cities (a), EU (b), and SEA (c). d–g, Observed probability distribution of ΔTs (d), population N (e), mean annual precipitation P (f), and urban green cover gc,u (g). Large circles in b, c indicate cities with green cover data20,22 used to compute the statistics in d–. Source:https://www.nature.com/articles/s41586-019-1512-9</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Unfortunately, UHI actual costs economic loss. Economist expected that climate change can cost a lot of money and impact every sector of the economy. It was expected that if UHI is intensifies, there will be higher cost for the city, which will be caused by the replacement of vegetation and bodies of water by concrete, asphalt, and other materials that trap more heat <span class="citation" data-cites="urbanhe2017">(<a href="#ref-urbanhe2017" role="doc-biblioref"><span>“Urban Heat Island Effect Could More Than Double Climate Costs for Cities”</span> 2017</a>)</span>. Socially, for Shanghai, it was expected that people from urban area would have much higher excess mortality rate due to hot related illness than those from exurban areas. Since this is not a local issue, but globally occurring in different metropolis, urban areas, hence some international regulations should be discussed below.</p>
<section id="global-policy" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="global-policy"><span class="header-section-number">8.1.1</span> Global policy</h3>
<p>From the perspective of the whole world, the urban population around the world has doubled from 1754 million in 1980 to 3,594 million in 2010, and this number will reach up to 5,167 million in 2030 (United Nations,&nbsp;<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/1477-8947.12245#narf12245-bib-0033"><strong>2018</strong></a>). It was predicted that by 2050, over 68% of the global population will be living in cities, the rapid urbanisation has caused the various problems, especially when urban areas actually only constitute less than 1% of the earth’s surface. UHI has become a more concerning issue across the globe. In 2021, the UN Environment Programme (UNEP) published detailed guidance to help the world combatting extreme heat, especially in urban areas where heating occurs twice the global average rate. THe book is caled <em>Beating the Heat: A Sustainable Cooling Handbook for Cities.</em> The handbook notes that the demand for space cooling increasing and the fact that urban heat is not evenly distributed. I think that the handbook has a lot of pages, which might be lengthy to most of the people. However, when it comes to city planning, I believe that city planner are going to find this handbook handy as it provides comprehensive overview of tools to cool cities sustainably and equitably. Also, with 80 supporting case studies that are currently running in the world, I think it would be useful for city planners to reference and create a more sustainable plan for cooling cities accordingly.</p>
<p>Below shows some of the case studies</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>City</th>
<th>Measures</th>
<th>Goals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Seoul, South Korea</strong></td>
<td>Restore the Cheonggyecheon stream that runs through the city replaced 5.8 kilometres of elevated expressway covering the stream with a mixed-use waterfront corridor.</td>
<td>The waterfront corridor decreased temperature 3.3°C to 5.9°C compared to a parallel road a few blocks away</td>
</tr>
<tr class="even">
<td><strong>Medellín, Colombia</strong></td>
<td>From 2016 to 2019, the city created 36 corridors, 18 along major roads and 18 along waterways, covering over 36 hectares.</td>
<td>The areas with green corridors have already seen temperature reductions of up to 4°C</td>
</tr>
<tr class="odd">
<td><strong>Guangzhou, China</strong></td>
<td>The municipal government adopted regional centralized cooling as part of a green and environmentally friendly modern urban centre in the core area of the Pearl River New City development</td>
<td>The local environmental temperature in the core area of Zhujiang New Town was reduced by 2-3°C compared to using distributed cooling systems.</td>
</tr>
</tbody>
</table>
<p>In remote sensing, it is capable to provide global and temporal observations to monitor the effects brought by UHI. One common way to capture data about UHI is through thermal mapping to monitor the Land Surface Temperature (LST). Other than UHI, Voogt and Oke (2003) suggested an alternative sub-classification analogous to UHI, called Surface Urban Heat Island (SUHI). The SUHI studies surface temperature differences between urban and rural areas, also addresses temporal variability.</p>
</section>
<section id="hong-kongs-uhi" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="hong-kongs-uhi"><span class="header-section-number">8.1.2</span> Hong Kong’s UHI</h3>
<p>In this practical, I have chosen my hometown Hong Kong to analysis the UHI with Landsat and MODIS. The reason I chose Hong Kong is because it is high density city situated in the sub-tropical climate region with hot and humid summer months. Hence, it is a city that suffers from UHI and is valuable to examine. I load up a level 2 administrative area to extract temperature data for Hong Kong in summer months from May to September. As mentioned in the practical, the data comes with Kelvin (K), converting it back to celcius (C), the formula is</p>
<pre><code>C = K - 273.15.</code></pre>
<p>Hence, with the ImageCollection extracted from “2018-01-01’, ’2022-12-10” in May to September, there are many images used. I have to put larger range in the date as the data is not sufficient with only 2 year, it did not cover the administrative area of Hong Kong. the <code>.subtract</code> doesn’t work on ImageCollection, so the 273.15 from the formula is adopted to subtract each image within the collection. After that, the reducer using mean as argument is used to create a map.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/week8_landsat.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Hong Kong’s Landsat image</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The same process is done with adopting another instrument called Moderate Resolution Imaging Spectroradiometer (MODIS). It is an instrument that aboard both Terra and Aqua satellites. The scale factor has to be applied because the resolution for MODIS data is at 1km resolution. Therefore, I used the scale factor to multiply by 0.02 and subtract with 273.1 (for the kelvin celcius change). In addition, I have adjusted the range of date from January to Octorber as the results are not very effective if I only include May to September.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/week8_modis.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Hong Kong’ MODIS Land Surface Temperature</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The time series for MODIS data from May to September is shown below. The range of temperature is not large, the average temperature is above 25 degrees, with only slight fluctuation. However, it can be seem that some days are above 35 degrees.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/week8_timeseries.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Hong Kong’ MODIS Land Surface Temperature</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="application" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="application"><span class="header-section-number">8.2</span> Application</h2>
<p>In the summary, I have covered the global policy on UHI, for application, I will use a local policy as an example on how cities have been adopting to combat and mitigate UHI.</p>
<section id="local-policy" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="local-policy"><span class="header-section-number">8.2.1</span> Local Policy</h3>
<section id="new-orleans-us" class="level4" data-number="8.2.1.1">
<h4 data-number="8.2.1.1" class="anchored" data-anchor-id="new-orleans-us"><span class="header-section-number">8.2.1.1</span> New Orleans, US</h4>
<p>In the US, Climate Central, nonprofit news organization, created an index to evaluate the intensity of urban heat islands and applied it to 159 cities across the U.S by measuring the type of land cover in each city, from greenspace to paved areas, and factoring in building height and population density. The cities with the five most intense urban heat islands are New Orleans, Newark, N.J., New York City, Houston, and San Francisco. According to a study by the Climate Central, on average the city is about 9 degrees hotter than the surrounding countryside.</p>
<p>The figure below illustrates the average surface temperatures in New Orleans from 2019 to 2021. The areas with higher temperature are areas with less than 10% of tree canopy. Hence, the authority has decided to implement plans to combat the rising surface temperature in urban areas.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://i0.wp.com/dirt.asla.org/wp-content/uploads/2023/01/23_01_19-Reforestation-Plan_Urban-Heat-Island_blog.jpg?w=625&amp;ssl=1" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Surface temperatures in New Orleans (2019-2021) Source:Spackman Mossop Michaels</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>To combat extreme heat, authority in New Orleans proposed a new master plan for rebuilding its urban forest calls for 100,000 new trees to be planted by 2040. It was hoping that the strategic planting of 100,000 trees could increase the tree canopy in each New Orleans neighborhood to cover at least 10% of the area. While trees and plants have a significant cooling benefit, the reforestation plan offers a more equitable model to reduce dangerous extreme heat while lowering energy use.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://npr.brightspotcdn.com/dims4/default/b7a6cc3/2147483647/strip/true/crop/2550x3300+0+0/resize/1760x2278!/format/webp/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F98%2Fe2%2F029e7ecd45e1b9265f94d9fe33c1%2F23-01-19-reforestation-plan-existing-tree-canopy-no-title.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">A mix of imagery and LiDAR paint a picture New Orleans’ tree canop Soruce:https://www.wwno.org/coastal-desk/2023-01-20/new-orleans-has-a-new-goal-for-building-a-greener-city-plant-100k-trees-in-20-years</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>I personally think that this approach is very pragmatic and reasonable, as trees area essentially the most effective and immediate effect to cool heat. In fact, most of the countries wen combating heat, they try to build trees to cool down the city. However, I am concerned about the maintenance and growth of the newlyplanted trees, just like what Madrid did with the metropolitan forest in week 4, the maintenance of the growth of trees are very important because it without proper management, trees might overgrown, the roots might damage structure etc. Hence, I think planting trees are a good method to combat UHI effects, but there is a need to properly manage afterwards, especially in an area that is already densely populated and dense with development.</p>
</section>
</section>
</section>
<section id="reflection" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="reflection"><span class="header-section-number">8.3</span> Reflection</h2>
<p>I think urban heat island is a topic that has be brought up for years, and I always felt the effects of UHI as Hong Kong is always really hot, not only because it is located within the suptropical climate, but definitely the high rise buildings, and the materials in densely populated urban areas have an effect on retaining and absorbing heat. One interesting fact is that Hong Kong rely on air conditioning heavily during summer time. Not only do shopping malls or public areas use air conditioning, even people at home turn on the air conditioner for full day because it is too hot. However, this actually creates a vicious cycle on UHI effects because it uses large amount of energy and produce more heat when it is turned on. to look broader, Greenhouse Gas (GHGs) and burning of fossil fuels to provide electricity for air conditioning might exercebate global warming.Hence, I think that not only from building things of the existing things to cool down surface, policies should also address issues like the excessive use of electricity on cooling, which actually contributes back to UHI.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-urbanhe2017" class="csl-entry" role="doc-biblioentry">
<span>“Urban Heat Island Effect Could More Than Double Climate Costs for Cities.”</span> 2017. <a href="https://news.mongabay.com/2017/06/urban-heat-island-effect-could-more-than-double-climate-costs-for-cities/">https://news.mongabay.com/2017/06/urban-heat-island-effect-could-more-than-double-climate-costs-for-cities/</a>.
</div>
<div id="ref-usepa2014" class="csl-entry" role="doc-biblioentry">
US EPA, OAR. 2014. <span>“Learn About Heat Islands.”</span> <a href="https://www.epa.gov/heatislands/learn-about-heat-islands">https://www.epa.gov/heatislands/learn-about-heat-islands</a>.
</div>
</div>
</section>

</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Week7.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Week 7</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>